Proyect/IPC2_201700841/IPC2_201700841/Models/Solitario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2_201700841.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solitario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solitario()
        {
            this.Detalle_Solitario = new HashSet<Detalle_Solitario>();
        }
    
        public int id_solitario { get; set; }
        public Nullable<int> id_us { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Solitario> Detalle_Solitario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

Proyect/IPC2_201700841/IPC2_201700841/Controllers/HomeController.cs
using IPC2_201700841.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPC2_201700841.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Inicio()
        {
            return View();
        }
        [HttpPost]//protocolo
        public ActionResult Index(string us, string contra) //us toma el texto escrito en el index
        {
            //if (TempData["Message"] != null)
            //   ViewBag.Message = TempData["Message"].ToString();
            try
            {
                
                using (Proyecto_IPC2 baseDatos = new Proyecto_IPC2()) //entitis es el entity framework
                {
                    var lista = from datos in baseDatos.Usuario
                                where datos.Nombre_usuario == us && datos.Contra.ToString() == contra
                                select datos;
                    if (lista.Count() > 0) //si hay usuarios en la lista
                    {
                        Usuario usuarios = lista.First(); //toma el primero y crea la sesion
                        Session["usuario"] = usuarios; //sesion del usiaro con el modelo
                    }
                    else
                    {
                        //el usuario es invalido, lo redirecciona automaticamente al registro de usuarios.
                        return Redirect("/Usuarios/Create");
                        //  return Content("Usuario invalio ingrese de nuevo sus creenciales"); //se va al registro porque no entro
                    }
                }
                // el usuario ingresa a su cuenta.
                //@TempData["Message"] = "prueba";
                return RedirectToAction("StartSesion"); //usuario valido
            }
            catch (Exception ex)
            {
                //return View(model);
            }
            return View();
        }
        public ActionResult StartSesion()
        {
            return View();
        }


        public ActionResult Solitario()
        {
            return View();
        }

    }
   
}

Proyect/IPC2_201700841/IPC2_201700841/Controllers/TableroController.cs
using System;
using System.Collections.Generic;
using IPC2_201700841.Models.ViewModels;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Xml;
using System.Data.SqlClient;
using System.Web.WebSockets;
using IPC2_201700841.Models;
using Microsoft.Ajax.Utilities;
using System.Security.Cryptography.X509Certificates;
using System.Security.Policy;
using System.Web.UI.Adapters;

namespace IPC2_201700841.Controllers
{
    //[HttpGet] // este metodo para hacer una posicion de resivir informacion de una pagina
    //[HttpPost] //enviar informacion hacia una pagina web, cualquier tipo de informacion
    public class TableroController : Controller
    {
        // GET: Tablero
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexVersus()
        {
            return View();
        }
        public ActionResult ElegirModo_Solitario()
        {
            return View();
        }
        public ActionResult ElegirModo_Versus()
        {
            return View();
        }

        public ActionResult AperturaPersonalizadaXColorSolitario()
        {
            return View();
        }

        public ActionResult AperturaSolitario() { return View(); }
        public ActionResult AperturaNormalXColorSolitario() { return View(); }

        public ActionResult AperturaVersus() { return View(); }
        public ActionResult AperturaPersonalizadaXColorVersus() { return View(); }

        public ActionResult AperturaNormalXColorVersus() { return View(); }

        public ActionResult TableroVersusXtreamPersonalizado() { return View(); }

        public ActionResult TableroSolitarioXtreamPersonalizado() { return View(); }
        public ActionResult IndexInversoSolitario()
        {
            return View();
        }
        public ActionResult IndexXtreamSolitario()
        {
            return View();
        }
        public ActionResult IndexXtreamVersus()
        {
            return View();
        }
        public ActionResult IndexInversoVersus()
        {
            return View();
        }

        public ActionResult EegirModoenXtreamSolitario() 
        {
            return View();
        }

        public ActionResult TableroSolitario(string f)
        {
            if (Session["juego"] == null)
            {
                ObtenerContenidoA i1 = new ObtenerContenidoA();
                i1.color = "blanco";
                i1.fila = 4;
                i1.columna = "D";
                ObtenerContenidoA i2 = new ObtenerContenidoA();
                i2.color = "negro";
                i2.fila = 4;
                i2.columna = "E";
                ObtenerContenidoA i3 = new ObtenerContenidoA();
                i3.color = "negro";
                i3.fila = 5;
                i3.columna = "D";
                ObtenerContenidoA i4 = new ObtenerContenidoA();
                i4.color = "blanco";
                i4.fila = 5;
                i4.columna = "E";
                List<ObtenerContenidoA> fichas = new List<ObtenerContenidoA>();
                fichas.Add(i1);
                fichas.Add(i2);
                fichas.Add(i3);
                fichas.Add(i4);
                Session["juego"] = fichas;
                if (f == "blanco") //para cuando cualquier usuario eliga una ficha de color negro le toca segundo
                {
                    var cero = 0;
                    Session["turno"] = cero;

                }
                else //para cuando el usuario eligio una ficha de color blanco le toca primero
                {
                    Session["turno"] = null;
                }
                return View("~/Views/Tablero/TableroSolitario.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
            else
            {
                return View("~/Views/Tablero/TableroSolitario.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
        }

        public ActionResult TableroSolitarioInverso(string f)
        {
            if (Session["juego"] == null)
            {
                ObtenerContenidoA i1 = new ObtenerContenidoA();
                i1.color = "blanco";
                i1.fila = 4;
                i1.columna = "D";
                ObtenerContenidoA i2 = new ObtenerContenidoA();
                i2.color = "negro";
                i2.fila = 4;
                i2.columna = "E";
                ObtenerContenidoA i3 = new ObtenerContenidoA();
                i3.color = "negro";
                i3.fila = 5;
                i3.columna = "D";
                ObtenerContenidoA i4 = new ObtenerContenidoA();
                i4.color = "blanco";
                i4.fila = 5;
                i4.columna = "E";
                List<ObtenerContenidoA> fichas = new List<ObtenerContenidoA>();
                fichas.Add(i1);
                fichas.Add(i2);
                fichas.Add(i3);
                fichas.Add(i4);
                Session["juego"] = fichas;
                if (f == "blanco") //para cuando cualquier usuario eliga una ficha de color negro le toca segundo
                {
                    var cero = 0;
                    Session["turno"] = cero;

                }
                else //para cuando el usuario eligio una ficha de color blanco le toca primero
                {
                    Session["turno"] = null;
                }
                return View("~/Views/Tablero/TableroSolitarioInverso.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
            else
            {
                return View("~/Views/Tablero/TableroSolitarioInverso.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
        }

        public ActionResult TableroSolitarioXtream(string f)
        {
            if (Session["juego"] == null)
            {
                ObtenerContenidoA i1 = new ObtenerContenidoA();
                i1.color = "blanco";
                i1.fila = 4;
                i1.columna = "D";
                ObtenerContenidoA i2 = new ObtenerContenidoA();
                i2.color = "negro";
                i2.fila = 4;
                i2.columna = "E";
                ObtenerContenidoA i3 = new ObtenerContenidoA();
                i3.color = "negro";
                i3.fila = 5;
                i3.columna = "D";
                ObtenerContenidoA i4 = new ObtenerContenidoA();
                i4.color = "blanco";
                i4.fila = 5;
                i4.columna = "E";
                List<ObtenerContenidoA> fichas = new List<ObtenerContenidoA>();
                fichas.Add(i1);
                fichas.Add(i2);
                fichas.Add(i3);
                fichas.Add(i4);
                Session["juego"] = fichas;
                if (f == "blanco") //para cuando cualquier usuario eliga una ficha de color negro le toca segundo
                {
                    var cero = 0;
                    Session["turno"] = cero;

                }
                else //para cuando el usuario eligio una ficha de color blanco le toca primero
                {
                    Session["turno"] = null;
                }
                return View("~/Views/Tablero/TableroSolitarioXtream.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
            else
            {
                return View("~/Views/Tablero/TableroSolitarioXtream.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
        }

        public ActionResult TableroVersusInverso(string f)
        {
            if (Session["juego"] == null)
            {
                ObtenerContenidoA i1 = new ObtenerContenidoA();
                i1.color = "blanco";
                i1.fila = 4;
                i1.columna = "D";
                ObtenerContenidoA i2 = new ObtenerContenidoA();
                i2.color = "negro";
                i2.fila = 4;
                i2.columna = "E";
                ObtenerContenidoA i3 = new ObtenerContenidoA();
                i3.color = "negro";
                i3.fila = 5;
                i3.columna = "D";
                ObtenerContenidoA i4 = new ObtenerContenidoA();
                i4.color = "blanco";
                i4.fila = 5;
                i4.columna = "E";
                List<ObtenerContenidoA> fichas = new List<ObtenerContenidoA>();
                fichas.Add(i1);
                fichas.Add(i2);
                fichas.Add(i3);
                fichas.Add(i4);
                Session["juego"] = fichas;
                if (f == "blanco") //para cuando cualquier usuario eliga una ficha de color negro le toca segundo
                {
                    var cero = 0;
                    Session["turno"] = cero;

                }
                else //para cuando el usuario eligio una ficha de color blanco le toca primero
                {
                    Session["turno"] = null;
                }
                return View("~/Views/Tablero/TableroVersusInverso.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
            else
            {
                return View("~/Views/Tablero/TableroVersusInverso.cshtml", (List<ObtenerContenidoA>)Session["juego"]);
            }
        }

        public ActionResult TableroVersusXtream(string f)
        {
            if (Session["juego"] == null)
            {
                ObtenerContenidoA i1 = new ObtenerContenidoA();
                i1.color = "blanco";
                i1.fila = 4;
                i1.columna = "D";
                ObtenerContenidoA i2 = new ObtenerContenidoA();
                i2.color = "negro";
                i2.fila = 4;
                i2.columna = "E";
                ObtenerContenidoA i3 = new ObtenerContenidoA();
                i3.color = "negro";
                i3.fila = 5;
                i3.columna = "D";
                ObtenerContenidoA i4 = new ObtenerContenidoA();
                i4.color = "blanco";
                i4.fila = 5;
                i4.columna = "E";

Proyect/IPC2_201700841/IPC2_201700841/Views/Home/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
    Layout = "~/Views/Master/IndexMaster.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            @*<img src="~/img/othello.png" />*@
        </div>
        <div class="col-md-3 espacio text-dark" style="color:white">

            <h1>Iniciar Sesion</h1>
            <form action="/Home/Index" method="post">
                <label>Usuario <input class="name" type="text" id="us" name="us" style="color:black" /></label>
                <br />
                <label>Contraseña <input class="pass" type="password" id="contra" name="contra" style="color:black" /></label>
                <br />
                <br />
                <input class="button" type="submit" value="Aceptar" name="button" id="button" />
                <br />
                <br />
            </form>

        </div>
    </div>

</div>

Proyect/IPC2_201700841/IPC2_201700841/Views/Home/Solitario.cshtml
@{
    ViewBag.Title = "Solitario";
    Layout = "~/Views/Master/Pagina_inicio_master.cshtml";
}

@* esta pagina es para cargar un archivo o darle siguiente para ir al tablero *@


@* comenzamos *@

@model IPC2_201700841.Models.ViewModels.ArchivoModel
<h2>Cargar Archivo</h2>
@using (Html.BeginForm("TableroSolitario", "Tablero", FormMethod.Post, new { enctype = "multipart/form-data" }))
{   
        <div>
            <div>
                <!--div para el archivo-->
                @*@Html.LabelFor(d => d.Archivo)*@
                @Html.TextBoxFor(d => d.Archivo, new { type = "file", accept = ".xml" })
                @Html.ValidationMessageFor(d => d.Archivo)
            </div>
            <div>
                <input type="submit" value="Aceptar" />
            </div>
        </div>
   
    <p />
    <p />
    <p />
}


@* finalizamos *@
<div class="botonTablero">
    <div class="col-md-4">
        <!--boton para cargar una partida guardada-->
        <form action="/Tablero/TableroSolitario" method="post">
            <input type="submit" value="Tablero" />
        </form>
    </div>
</div>

Proyect/IPC2_201700841/IPC2_201700841/Views/Home/StartSesion.cshtml
@{
    ViewBag.Title = "StartSesion";
    Layout = "~/Views/Master/Pagina_inicio_master.cshtml";
}
<link href="~/Content/Paginas_Varias.css" rel="stylesheet" />
<div class="primero">
    <h1>BIENVENIDO A OTHELLO</h1>
</div>
<br />
<br />
<div class="tablero">
    <table align="center">
        <tr>
            <!--fila-->
            <th>
                <!--numero-->
            </th>
            <th>
                <!--columnna-->
                A
            </th>
            <th>
                B
            </th>
            <th>
                <!--columnna-->
                C
            </th>
            <th>
                D
            </th>
            <th>
                <!--columnna-->
                E
            </th>
            <th>
                F
            </th>
            <th>
                <!--columnna-->
                G
            </th>
            <th>
                H
            </th>
        </tr> <!--contiene la fila de las letras-->

        <tr>
            <!--fila-->
            <th>
                1
            </th>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                2
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                3
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img//verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>
        <tr>
            <!--fila-->
            <td>
                4
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/blanco.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/negro.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                5
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/negro.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/blanco.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                6
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                7
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

        <tr>
            <!--fila-->
            <td>
                8
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img//verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <!--columnna-->
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
            <td>
                <img src="~/img/verde.jpg" width="50" height="50" />
            </td>
        </tr>

    </table>
</div>
<div class="primero">
    <h2>Modos de Juego</h2>
</div>
<div class="Botones">
    <div class="Boton1">
        <div class="col-md-3">
            <!--boton para cargar una partida guardada-->
            <form action="../Tablero/Index" method="post">
                    <input type="submit" value="Solitario" />
                
                </form>
            
            @*<input type="submit" value="Solitario" />*@

            @*este solitario es primero para sargar un archivo, si no se quiere cargar el archivo
            entonces solo darle siguiente o algun otro boton para ir al tablero*@

        </div>
    </div>
    <div class="Boton2">
        <div class="col-md-3">
            <!--boton para cargar una partida guardada-->
            @*<form action="/Home/Contact" method="post">
                    <input type="submit" value="Versus" />
                </form>*@
            <form action="../Tablero/IndexVersus" method="post">
                <input type="submit" value="Versus" />
            </form>
            
        </div>
    </div>

    <div class="Boton3">
        <div class="col-md-3">
            <!--boton para cargar una partida guardada-->
            @*<form action="/Home/Contact" method="post">
                    <input type="submit" value="Torneo" />
                </form>*@

            <input type="submit" value="Torneo" />
        </div>

    </div>
</div>

    